--------------------------------------------------------
--  DDL for Table APP_STATIC_DOMAIN
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."APP_STATIC_DOMAIN" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"RWNO" NUMBER, 
	"VALU" VARCHAR2(3 BYTE), 
	"DOMN_DESC" VARCHAR2(250 BYTE), 
	"REGN_LANG" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;
