--------------------------------------------------------
--  Constraints for Table APP_DYNAMIC_DOMAIN
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."APP_DYNAMIC_DOMAIN" MODIFY ("REF_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."APP_DYNAMIC_DOMAIN" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."APP_DYNAMIC_DOMAIN" ADD CONSTRAINT "PK_ADYM" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
