--------------------------------------------------------
--  Constraints for Table APP_STATIC_DOMAIN
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."APP_STATIC_DOMAIN" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."APP_STATIC_DOMAIN" MODIFY ("VALU" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."APP_STATIC_DOMAIN" MODIFY ("REGN_LANG" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."APP_STATIC_DOMAIN" ADD CONSTRAINT "PK_ASDM" PRIMARY KEY ("CODE", "VALU", "REGN_LANG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
