--------------------------------------------------------
--  DDL for Table APP_DYNAMIC_DOMAIN
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."APP_DYNAMIC_DOMAIN" 
   (	"REF_CODE" RAW(16), 
	"CODE" RAW(16), 
	"DOMN_NAME" VARCHAR2(100 BYTE), 
	"DOMN_CMNT" VARCHAR2(100 BYTE), 
	"RWNO" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"DOMN_DESC" VARCHAR2(250 BYTE), 
	"REGN_LANG" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."DOMN_NAME" IS 'Latin table name for domain';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."DOMN_CMNT" IS 'Persian table name for description';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."RWNO" IS 'Row number';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."NAME" IS 'Latin row description';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."DOMN_DESC" IS 'Row value description';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."REGN_LANG" IS 'Langugaues';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."APP_DYNAMIC_DOMAIN"."DEL_DATE" IS 'تاریخ حذف';
