--------------------------------------------------------
--  DDL for Table BOX_PRIVILEGE
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."BOX_PRIVILEGE" 
   (	"SYS_CODE" RAW(16), 
	"CODE" RAW(16), 
	"BOXP_NAME" VARCHAR2(100 BYTE), 
	"BOXP_DESC" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."BOX_PRIVILEGE"."SYS_CODE" IS 'کد زیر سیستم';
   COMMENT ON COLUMN "FCEO$KRNL"."BOX_PRIVILEGE"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."BOX_PRIVILEGE"."BOXP_NAME" IS 'نام جعبه دسترسی';
   COMMENT ON COLUMN "FCEO$KRNL"."BOX_PRIVILEGE"."BOXP_DESC" IS 'عنوان';
