--------------------------------------------------------
--  DDL for Table BROADCAST_CONFIG
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."BROADCAST_CONFIG" 
   (	"CODE" RAW(16), 
	"BRDC_TYPE" VARCHAR2(3 BYTE), 
	"BGWK_STAT" VARCHAR2(3 BYTE), 
	"BGWK_INTR" NUMBER, 
	"WEB_SITE" VARCHAR2(500 BYTE), 
	"LOGN_TYPE" VARCHAR2(3 BYTE), 
	"USER_NAME" VARCHAR2(250 BYTE), 
	"PASS_WORD" VARCHAR2(250 BYTE), 
	"WEB_SITE_LOGN" VARCHAR2(250 BYTE), 
	"WEB_SITE_PSWD" VARCHAR2(250 BYTE), 
	"ACES_KEY" VARCHAR2(250 BYTE), 
	"SCRT_KEY" VARCHAR2(250 BYTE), 
	"TOKN_CODE" VARCHAR2(250 BYTE), 
	"LINE_NUMB" VARCHAR2(50 BYTE), 
	"DFLT_STAT" VARCHAR2(3 BYTE), 
	"FTCH_ROW_NUMB" NUMBER, 
	"MIN_STOP_CHRG" NUMBER, 
	"SERV_TYPE" VARCHAR2(3 BYTE), 
	"COMP_SNDR" VARCHAR2(200 BYTE), 
	"SLEP_INTR" NUMBER, 
	"PING_HOST" VARCHAR2(50 BYTE), 
	"SEND_STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."BRDC_TYPE" IS 'نوع خط ارسال
پیامک
بله
تلگرام';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."BGWK_STAT" IS 'وضعیت سامانه ارسال';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."BGWK_INTR" IS 'تایم ارسال و نوبت ارسال بعدی';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."WEB_SITE" IS 'وب سایت';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."LOGN_TYPE" IS 'نوع احراز هویت';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."LINE_NUMB" IS 'شماره خط ارسال';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."BROADCAST_CONFIG"."DEL_DATE" IS 'تاریخ حذف';
