--------------------------------------------------------
--  DDL for Trigger CG$ADML_PGAT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FCEO$KRNL"."CG$ADML_PGAT" 
AFTER DELETE OR INSERT OR UPDATE
ON PAYMENT_GATEWAY
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING THEN
    NULL;
  ELSIF UPDATING THEN
    NULL;
  ELSIF DELETING THEN
    NULL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END CG$ADML_PGAT;
/
ALTER TRIGGER "FCEO$KRNL"."CG$ADML_PGAT" ENABLE;
