--------------------------------------------------------
--  DDL for Trigger CG$ADML_UAIN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FCEO$KRNL"."CG$ADML_UAIN" 
AFTER DELETE OR INSERT OR UPDATE
ON USER_APPLICATION_INSTANCE
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING THEN
    NULL;
  ELSIF UPDATING THEN
    NULL;
  ELSIF DELETING THEN
    NULL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END CG$ADML_UAIN;
/
ALTER TRIGGER "FCEO$KRNL"."CG$ADML_UAIN" ENABLE;
