--------------------------------------------------------
--  DDL for Trigger CG$ADML_RLSR
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FCEO$KRNL"."CG$ADML_RLSR" 
AFTER DELETE OR INSERT OR UPDATE
ON ROLE_SYSTEM_REPORT
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING THEN
    NULL;
  ELSIF UPDATING THEN
    NULL;
  ELSIF DELETING THEN
    NULL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END CG$ADML_RLSR;
/
ALTER TRIGGER "FCEO$KRNL"."CG$ADML_RLSR" ENABLE;
