--------------------------------------------------------
--  DDL for Trigger CG$ADML_URTK
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FCEO$KRNL"."CG$ADML_URTK" 
AFTER DELETE OR INSERT OR UPDATE
ON USER_REFRESH_TOKEN
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING THEN
    NULL;
  ELSIF UPDATING THEN
    NULL;
  ELSIF DELETING THEN
    NULL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END CG$ADML_URTK;
/
ALTER TRIGGER "FCEO$KRNL"."CG$ADML_URTK" ENABLE;
