--------------------------------------------------------
--  DDL for Trigger CG$ADML_USON
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FCEO$KRNL"."CG$ADML_USON" 
AFTER DELETE OR INSERT OR UPDATE
ON USER_HOST_SESSION
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING THEN
    NULL;
  ELSIF UPDATING THEN
    NULL;
  ELSIF DELETING THEN
    NULL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END CG$ADML_USON;
/
ALTER TRIGGER "FCEO$KRNL"."CG$ADML_USON" ENABLE;
