--------------------------------------------------------
--  DDL for Trigger CG$ADML_SYSR
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FCEO$KRNL"."CG$ADML_SYSR" 
AFTER DELETE OR INSERT OR UPDATE
ON SYSTEM_REPORT
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING THEN
    NULL;
  ELSIF UPDATING THEN
    NULL;
  ELSIF DELETING THEN
    NULL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END CG$ADML_SYSR;
/
ALTER TRIGGER "FCEO$KRNL"."CG$ADML_SYSR" ENABLE;
