--------------------------------------------------------
--  DDL for Trigger CG$ADML_SRRH
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FCEO$KRNL"."CG$ADML_SRRH" 
AFTER DELETE OR INSERT OR UPDATE
ON ROLE_SYSTEM_REPORT_HISTORY
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING THEN
    NULL;
  ELSIF UPDATING THEN
    NULL;
  ELSIF DELETING THEN
    NULL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END CG$ADML_SRRH;
/
ALTER TRIGGER "FCEO$KRNL"."CG$ADML_SRRH" ENABLE;
