--------------------------------------------------------
--  DDL for Trigger CG$BDML_USRA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FCEO$KRNL"."CG$BDML_USRA" 
BEFORE DELETE OR INSERT OR UPDATE
ON USER_APPLICATION
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING THEN
    :N.CODE := SYS_GUID();
    :N.CRET_DATE := SYSDATE;
    :N.SALT_KEY := SYS_GUID();
    SELECT NVL(APP_CNTX_PKG.GET_CNTX_U('userappname'), USER)
      INTO :N.CRET_BY
      FROM dual;
  ELSIF UPDATING THEN
    :N.MDFY_DATE := SYSDATE;
    SELECT NVL(APP_CNTX_PKG.GET_CNTX_U('userappname'), USER)
      INTO :N.MDFY_BY
      FROM dual;
    NULL;
  ELSIF DELETING THEN
    NULL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END CG$BDML_USRA;
/
ALTER TRIGGER "FCEO$KRNL"."CG$BDML_USRA" ENABLE;
