--------------------------------------------------------
--  DDL for Trigger CG$BDML_PGAT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "FCEO$KRNL"."CG$BDML_PGAT" 
BEFORE DELETE OR INSERT OR UPDATE
ON PAYMENT_GATEWAY 
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING THEN
    :N.CODE := SYS_GUID();
    :N.CRET_DATE := SYSDATE;
    SELECT NVL(APP_CNTX_PKG.GET_CNTX_U('userappname'), USER)
      INTO :N.CRET_BY
      FROM dual;
  ELSIF UPDATING THEN
    :N.MDFY_DATE := SYSDATE;
    SELECT NVL(APP_CNTX_PKG.GET_CNTX_U('userappname'), USER)
      INTO :N.MDFY_BY
      FROM dual;
  ELSIF DELETING THEN
    NULL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END CG$BDML_PGAT;
/
ALTER TRIGGER "FCEO$KRNL"."CG$BDML_PGAT" ENABLE;
