--------------------------------------------------------
--  DDL for Table CONNECTION_STRING
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."CONNECTION_STRING" 
   (	"DSRC_CODE" RAW(16), 
	"USRA_CODE" RAW(16), 
	"CODE" RAW(16), 
	"CNCT_STRN_DNRM" VARCHAR2(200 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."DSRC_CODE" IS 'کد منبع اطلاعات';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."USRA_CODE" IS 'کد  کاربر';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."CNCT_STRN_DNRM" IS 'رشته اتصال به پایگاه داده';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."STAT" IS 'وضعیت';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."CONNECTION_STRING"."DEL_DATE" IS 'تاریخ حذف';
