--------------------------------------------------------
--  DDL for Table DATASOURCE
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."DATASOURCE" 
   (	"SYS_CODE" RAW(16), 
	"CODE" RAW(16), 
	"HOST_IP_ADRS" VARCHAR2(50 BYTE), 
	"PORT_NUMB" NUMBER, 
	"SID" VARCHAR2(100 BYTE), 
	"ROOT_NAME" VARCHAR2(30 BYTE), 
	"ROOT_DESC" VARCHAR2(100 BYTE), 
	"SCHM_NAME" VARCHAR2(30 BYTE), 
	"PASS_WORD" VARCHAR2(200 BYTE), 
	"SALT_KEY" RAW(32), 
	"STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."SYS_CODE" IS 'کد زیر سیستم';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."HOST_IP_ADRS" IS 'IP Address';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."PORT_NUMB" IS 'شماره پورت';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."SID" IS 'کد شناسه پایگاه داده';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."ROOT_NAME" IS 'نام پایگاه داده';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."ROOT_DESC" IS 'توضیحات پایگاه داده';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."SCHM_NAME" IS 'کاربر و اسکیما پایگاه داده';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."PASS_WORD" IS 'رمز عبور';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."SALT_KEY" IS 'کلیذ رمز گشایی';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."STAT" IS 'وضعیت';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."DATASOURCE"."DEL_DATE" IS 'تاریخ حذف';
