--------------------------------------------------------
--  File created - Thursday-June-04-2026   
--------------------------------------------------------
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_DYNAMIC_DOMAIN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_STATIC_DOMAIN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BOX_PRIVILEGE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BROADCAST_CONFIG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CONNECTION_STRING_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DATASOURCE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_USER_APPLICATION_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\HOST_INFORMATION_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\MESSAGE_BOX_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\NEWS_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_GATEWAY_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_TRANSACTION_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PRIVILEGE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_HISTORY_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_HISTORY_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_HISTORY_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_APPLICATION_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_AUDIT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_REPORT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TABLE_ALIAS_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TEMP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TEMPLATE_ITEM_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_HISTORY_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PAYMENT_GATEWAY_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_HISTORY_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_HISTORY_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_HOST_SESSION_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_IMAGE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_NOTIFICATION_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_ACTV_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_ATYP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_CONF_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_CYCL_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_LOGT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_PERM_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_PMST_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_RCST_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_RGLN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_WKDY_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_YSNO_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\V_USRA_CSTR_DSRC_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_DYNAMIC_DOMAIN_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_STATIC_DOMAIN_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BOX_PRIVILEGE_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BROADCAST_CONFIG_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CONNECTION_STRING_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DATASOURCE_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_USER_APPLICATION_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\HOST_INFORMATION_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\MESSAGE_BOX_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\NEWS_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_GATEWAY_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_TRANSACTION_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PRIVILEGE_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_HISTORY_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_HISTORY_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_HISTORY_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_APPLICATION_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_AUDIT_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_REPORT_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TABLE_ALIAS_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TEMPLATE_ITEM_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_HISTORY_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PAYMENT_GATEWAY_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_HISTORY_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_HISTORY_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_HOST_SESSION_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_IMAGE_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_NOTIFICATION_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_DATA_TABLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ADYM_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ASDM_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_BOXP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_BRDC_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_CSTR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_DSRC_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_GPUA_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_GROP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_HINF_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_MSGB_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_NEWS_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_PGAT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_PRVL_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_PTRN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_RLPH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_RLSR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ROLE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ROLH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ROLP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_SRRH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_SYS_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_SYSD_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_SYSR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_TBLA_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_TMPI_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UAIH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UAIN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UAPH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UAPR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UARH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UARL_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UIMG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UNOT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_URTK_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_USON_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_USRA_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\UK_ROLE_ROLE_NAME_SYS_CODE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\UK_USRA_EMAL_ADRS_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\UK_USRA_PHON_NUMB_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\UK_USRA_USER_APP_NAME_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_USON_CODE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_TOKN_HASH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_TOKN_FMLY_CODE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_USRA_CODE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_HINF_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_PGAT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_PTRN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_RLSR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_SRRH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_SYSR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_UAIH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_UAIN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_URTK_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_USON_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_USRA_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_AUPD_ROLE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_AUPD_ROLP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_AUPD_UAPR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_AUPD_UARL_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_HINF_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_PGAT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_PTRN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_RLSR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_SRRH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_SYSR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_UAIH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_UAIN_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_URTK_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_USON_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_USRA_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ADYM_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ASDM_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_BOXP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_BRDC_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_CSTR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_DSRC_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_GPUA_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_GROP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_MSGB_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_NEWS_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_PRVL_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_RLPH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ROLE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ROLH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ROLP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_SYSD_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UAPH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UAPR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UARH_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UARL_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UIMG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UNOT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_BRDC_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_CSTR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_DSRC_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_GPUA_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_GROP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_MSGB_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_NEWS_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_ROLE_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_ROLP_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_UAPR_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_UARL_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_UIMG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CRET_ADYM_P_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CRET_ASDM_P_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_CNTX_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ADYM_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ASDM_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_BOXP_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_BRDC_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_CSTR_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_DSRC_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_GPUA_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_GROP_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_HINF_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_MSGB_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_NEWS_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PGAT_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PRVL_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PTRN_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_RLSR_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ROLE_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ROLP_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SRRH_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYSD_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYSR_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYS_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAIH_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAIN_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAPR_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UARL_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UIMG_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UINC_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UNOT_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_URTK_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_USON_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_USRA_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ADYM_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ASDM_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_BOXP_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_BRDC_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_CSTR_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_DSRC_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_GPUA_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_GROP_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_HINF_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_MSGB_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_NEWS_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PGAT_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PRVL_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PTRN_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_RLSR_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ROLE_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ROLP_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SRRH_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SYSR_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SYS_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAIH_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAIN_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAPR_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UARL_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UIMG_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UNOT_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_URTK_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_USON_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_USRA_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ADYM_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ASDM_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_BOXP_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_CSTR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_DSRC_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_GPUA_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_GROP_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_HINF_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_NEWS_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_PGAT_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_PRVL_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_PTRN_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_RLSR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ROLE_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ROLP_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SRRH_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SYSD_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SYSR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SYS_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UAIH_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UAIN_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UAPR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UIMG_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UINC_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UINS_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UNOT_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_URTK_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_USON_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_USRA_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PBLC_COMN_PKG_2.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_CNTX_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ADYM_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ASDM_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_BOXP_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_BRDC_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_CSTR_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_DSRC_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_GPUA_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_GROP_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_HINF_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_MSGB_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_NEWS_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PGAT_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PRVL_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PTRN_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_RLSR_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ROLE_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ROLP_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SRRH_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYSD_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYSR_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYS_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAIH_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAIN_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAPR_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UARL_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UIMG_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UINC_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UNOT_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_URTK_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_USON_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_USRA_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ADYM_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ASDM_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_BOXP_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_BRDC_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_CSTR_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_DSRC_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_GPUA_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_GROP_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_HINF_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_MSGB_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_NEWS_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PGAT_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PRVL_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PTRN_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_RLSR_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ROLE_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ROLP_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SRRH_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SYSR_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SYS_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAIN_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAPR_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UARL_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UIMG_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UNOT_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_URTK_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_USON_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_USRA_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ASDM_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SYSD_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PBLC_COMN_PKG_3.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_MLDS_U_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_MSDS_U_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_NVID_U_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_SLDM_U_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_SSDM_U_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_HISTORY_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_HOST_SESSION_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_REPORT_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_HISTORY_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_HISTORY_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CONNECTION_STRING_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DATASOURCE_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_GATEWAY_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_APPLICATION_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BOX_PRIVILEGE_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TEMPLATE_ITEM_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_HISTORY_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_TRANSACTION_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BROADCAST_CONFIG_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_STATIC_DOMAIN_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_DYNAMIC_DOMAIN_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_IMAGE_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\NEWS_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_NOTIFICATION_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PAYMENT_GATEWAY_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\HOST_INFORMATION_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TABLE_ALIAS_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PRIVILEGE_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_USER_APPLICATION_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_HISTORY_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\MESSAGE_BOX_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_AUDIT_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_HISTORY_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_CONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_DYNAMIC_DOMAIN_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BOX_PRIVILEGE_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CONNECTION_STRING_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DATASOURCE_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_USER_APPLICATION_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\MESSAGE_BOX_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_GATEWAY_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_TRANSACTION_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PRIVILEGE_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_HISTORY_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_HISTORY_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_HISTORY_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_AUDIT_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_REPORT_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TEMPLATE_ITEM_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_HISTORY_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PAYMENT_GATEWAY_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_HISTORY_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_HISTORY_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_HOST_SESSION_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_IMAGE_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_NOTIFICATION_REFCONSTRAINT_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_REFCONSTRAINT_1.sql
