--------------------------------------------------------
--  File created - Wednesday-June-03-2026   
--------------------------------------------------------
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_DYNAMIC_DOMAIN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_STATIC_DOMAIN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BOX_PRIVILEGE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BROADCAST_CONFIG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CONNECTION_STRING.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DATASOURCE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_USER_APPLICATION.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\HOST_INFORMATION.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\MESSAGE_BOX.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\NEWS.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_GATEWAY.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_TRANSACTION.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PRIVILEGE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_HISTORY.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_HISTORY.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_HISTORY.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_APPLICATION.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_AUDIT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_REPORT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TABLE_ALIAS.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TEMP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TEMPLATE_ITEM.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_HISTORY.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PAYMENT_GATEWAY.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_HISTORY.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_HISTORY.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_HOST_SESSION.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_IMAGE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_NOTIFICATION.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_ACTV.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_ATYP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_CONF.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_CYCL.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_LOGT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_PERM.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_PMST.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_RCST.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_RGLN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_WKDY.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\D_YSNO.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\V_USRA_CSTR_DSRC.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ADYM.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ASDM.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_BOXP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_BRDC.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_CSTR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_DSRC.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_GPUA.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_GROP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_HINF.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_MSGB.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_NEWS.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_PGAT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_PRVL.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_PTRN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_RLPH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_RLSR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ROLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ROLH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_ROLP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_SRRH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_SYS.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_SYSD.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_SYSR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_TBLA.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_TMPI.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UAIH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UAIN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UAPH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UAPR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UARH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UARL.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UIMG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_UNOT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_URTK.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_USON.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PK_USRA.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\UK_ROLE_ROLE_NAME_SYS_CODE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\UK_USRA_EMAL_ADRS.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\UK_USRA_PHON_NUMB.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\UK_USRA_USER_APP_NAME.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_USON_CODE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_TOKN_HASH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_TOKN_FMLY_CODE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_USRA_CODE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_HINF.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_PGAT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_PTRN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_RLSR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_SRRH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_SYSR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_UAIH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_UAIN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_URTK.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_USON.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_ADML_USRA.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_AUPD_ROLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_AUPD_ROLP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_AUPD_UAPR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_AUPD_UARL.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_HINF.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_PGAT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_PTRN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_RLSR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_SRRH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_SYSR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_UAIH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_UAIN.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_URTK.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_USON.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BDML_USRA.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ADYM.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ASDM.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_BOXP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_BRDC.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_CSTR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_DSRC.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_GPUA.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_GROP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_MSGB.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_NEWS.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_PRVL.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_RLPH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ROLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ROLH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_ROLP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_SYSD.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UAPH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UAPR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UARH.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UARL.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UIMG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BINS_UNOT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_BRDC.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_CSTR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_DSRC.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_GPUA.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_GROP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_MSGB.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_NEWS.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_ROLE.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_ROLP.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_UAPR.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_UARL.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CG_BUPD_UIMG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CRET_ADYM_P.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CRET_ASDM_P.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_CNTX_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ADYM_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ASDM_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_BOXP_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_BRDC_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_CSTR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_DSRC_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_GPUA_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_GROP_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_HINF_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_MSGB_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_NEWS_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PGAT_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PRVL_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PTRN_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_RLSR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ROLE_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ROLP_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SRRH_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYSD_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYSR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYS_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAIH_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAPR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UARL_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UIMG_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UINC_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UINS_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UNOT_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_URTK_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_USON_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_USRA_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ADYM_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ASDM_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_BOXP_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_BRDC_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_CSTR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_DSRC_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_GPUA_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_GROP_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_HINF_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_MSGB_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_NEWS_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PGAT_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PRVL_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PTRN_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_RLSR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ROLE_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ROLP_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SRRH_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SYSR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SYS_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAIH_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAIN_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAPR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UARL_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UIMG_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UNOT_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_URTK_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_USON_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_USRA_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ADYM_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ASDM_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_BOXP_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_CSTR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_DSRC_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_GPUA_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_GROP_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_HINF_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_NEWS_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_PGAT_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_PRVL_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_PTRN_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_RLSR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ROLE_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ROLP_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SRRH_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SYSD_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SYSR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SYS_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UAIH_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UAPR_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UIMG_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UINC_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UINS_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_UNOT_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_URTK_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_USON_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_USRA_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PBLC_COMN_PKG.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_CNTX_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ADYM_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ASDM_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_BOXP_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_BRDC_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_CSTR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_DSRC_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_GPUA_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_GROP_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_HINF_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_MSGB_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_NEWS_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PGAT_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PRVL_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_PTRN_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_RLSR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ROLE_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_ROLP_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SRRH_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYSD_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYSR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_SYS_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAIH_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UAPR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UARL_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UIMG_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UINC_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UINS_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_UNOT_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_URTK_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_USON_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DML_USRA_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ADYM_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ASDM_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_BOXP_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_BRDC_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_CSTR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_DSRC_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_GPUA_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_GROP_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_HINF_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_MSGB_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_NEWS_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PGAT_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PRVL_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_PTRN_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_RLSR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ROLE_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_ROLP_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SRRH_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SYSR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_SYS_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAIN_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UAPR_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UARL_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UIMG_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_UNOT_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_URTK_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_USON_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\EXTR_USRA_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_ASDM_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\INTR_SYSD_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PBLC_COMN_PKG_1.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_MLDS_U.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_MSDS_U.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_NVID_U.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_SLDM_U.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GET_SSDM_U.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_HISTORY_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_HOST_SESSION_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_REPORT_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_HISTORY_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_HISTORY_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CONNECTION_STRING_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DATASOURCE_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_GATEWAY_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_APPLICATION_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BOX_PRIVILEGE_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TEMPLATE_ITEM_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_HISTORY_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_TRANSACTION_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BROADCAST_CONFIG_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_STATIC_DOMAIN_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_DYNAMIC_DOMAIN_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_IMAGE_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\NEWS_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_NOTIFICATION_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PAYMENT_GATEWAY_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\HOST_INFORMATION_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TABLE_ALIAS_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PRIVILEGE_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_USER_APPLICATION_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_HISTORY_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\MESSAGE_BOX_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_AUDIT_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_HISTORY_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_CONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\APP_DYNAMIC_DOMAIN_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\BOX_PRIVILEGE_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\CONNECTION_STRING_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\DATASOURCE_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\GROUPING_USER_APPLICATION_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\MESSAGE_BOX_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_GATEWAY_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PAYMENT_TRANSACTION_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\PRIVILEGE_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_HISTORY_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_PRIVILEGE_HISTORY_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\ROLE_SYSTEM_REPORT_HISTORY_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_AUDIT_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\SYSTEM_REPORT_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\TEMPLATE_ITEM_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_INSTANCE_HISTORY_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PAYMENT_GATEWAY_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_PRIVILEGE_HISTORY_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_APPLICATION_ROLE_HISTORY_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_HOST_SESSION_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_IMAGE_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_NOTIFICATION_REFCONSTRAINT.sql
@D:\Projects\OracleDatabase\Fceo$Krnl\USER_REFRESH_TOKEN_REFCONSTRAINT.sql
