REM INSERTING into FCEO$KRNL.GROUPING
SET DEFINE OFF;
Insert into FCEO$KRNL.GROUPING (CODE,GROP_NAME,GROP_DESC,CRET_BY,CRET_DATE,MDFY_BY,MDFY_DATE,DEL_BY,DEL_DATE) values ('E84946FA519D4EF69E698D6E91988A1E','IT MAN','مسئول انفورماتیک','FCEO$KRNL',to_date('12-OCT-25','DD-MON-RR'),'FCEO$KRNL',to_date('12-OCT-25','DD-MON-RR'),null,null);
Insert into FCEO$KRNL.GROUPING (CODE,GROP_NAME,GROP_DESC,CRET_BY,CRET_DATE,MDFY_BY,MDFY_DATE,DEL_BY,DEL_DATE) values ('15AD6FB6C75E44958C884164B8F5ED3B','IT Supporter man','مسئول پشتیبانی','FCEO$KRNL',to_date('12-OCT-25','DD-MON-RR'),'FCEO$KRNL',to_date('12-OCT-25','DD-MON-RR'),null,null);
Insert into FCEO$KRNL.GROUPING (CODE,GROP_NAME,GROP_DESC,CRET_BY,CRET_DATE,MDFY_BY,MDFY_DATE,DEL_BY,DEL_DATE) values ('8E90D03A35244B81BBB464A2D32325FD','Finannce','مسئول مالی','FCEO$KRNL',to_date('12-OCT-25','DD-MON-RR'),'FCEO$KRNL',to_date('12-OCT-25','DD-MON-RR'),null,null);
