--------------------------------------------------------
--  Constraints for Table GROUPING_USER_APPLICATION
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."GROUPING_USER_APPLICATION" MODIFY ("GROP_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."GROUPING_USER_APPLICATION" MODIFY ("USRA_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."GROUPING_USER_APPLICATION" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."GROUPING_USER_APPLICATION" ADD CONSTRAINT "PK_GPUA" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
