--------------------------------------------------------
--  DDL for Table GROUPING_USER_APPLICATION
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."GROUPING_USER_APPLICATION" 
   (	"GROP_CODE" RAW(16), 
	"USRA_CODE" RAW(16), 
	"CODE" RAW(16), 
	"STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."GROUPING_USER_APPLICATION"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."GROUPING_USER_APPLICATION"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."GROUPING_USER_APPLICATION"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."GROUPING_USER_APPLICATION"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."GROUPING_USER_APPLICATION"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."GROUPING_USER_APPLICATION"."DEL_DATE" IS 'تاریخ حذف';
