--------------------------------------------------------
--  Ref Constraints for Table GROUPING_USER_APPLICATION
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."GROUPING_USER_APPLICATION" ADD CONSTRAINT "FK_GPUA_GROP" FOREIGN KEY ("GROP_CODE")
	  REFERENCES "FCEO$KRNL"."GROUPING" ("CODE") ENABLE;
  ALTER TABLE "FCEO$KRNL"."GROUPING_USER_APPLICATION" ADD CONSTRAINT "FK_GPUA_USRA" FOREIGN KEY ("USRA_CODE")
	  REFERENCES "FCEO$KRNL"."USER_APPLICATION" ("CODE") ENABLE;
