--------------------------------------------------------
--  DDL for Table HOST_INFORMATION
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."HOST_INFORMATION" 
   (	"CODE" RAW(16), 
	"DEV_NAME" VARCHAR2(200 BYTE), 
	"PLAT_FORM_TYPE" VARCHAR2(3 BYTE), 
	"PLAT_FORM" VARCHAR2(100 BYTE), 
	"OS_TYPE" VARCHAR2(3 BYTE), 
	"OS_VERS" VARCHAR2(20 BYTE), 
	"IP_ADRS" VARCHAR2(17 BYTE), 
	"AGNT_DESC" VARCHAR2(100 BYTE), 
	"APP_VER" VARCHAR2(17 BYTE), 
	"MAC_ADRS" VARCHAR2(17 BYTE), 
	"ACTV_STAT" VARCHAR2(3 BYTE), 
	"LAST_LGIN_DNRM" TIMESTAMP (0), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."DEV_NAME" IS 'نام دستگاه';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."PLAT_FORM_TYPE" IS 'نوع پلتفرم وب ، موبایل، کامپیوتر';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."PLAT_FORM" IS 'توضیحات پلتفرم';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."OS_TYPE" IS 'نوع سیستم عامل';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."OS_VERS" IS 'نسخه سیستم عامل';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."IP_ADRS" IS 'IP Address';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."AGNT_DESC" IS 'نوع مرورگر';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."APP_VER" IS 'نسخه نرم افزار';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."MAC_ADRS" IS 'Mac Address';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."ACTV_STAT" IS 'وضعیت دستگاه';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."LAST_LGIN_DNRM" IS 'آخرین زمان اتصال';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."HOST_INFORMATION"."MDFY_DATE" IS 'تاریخ ویرایش';
