--------------------------------------------------------
--  DDL for Table MESSAGE_BOX
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."MESSAGE_BOX" 
   (	"BRDC_CODE" RAW(16), 
	"CODE" RAW(16), 
	"SYS_CODE" RAW(16), 
	"BRDC_TYPE_DNRM" VARCHAR2(3 BYTE), 
	"SEND_DATE" DATE, 
	"REF_CODE" RAW(16), 
	"PHON_NUMB" VARCHAR2(11 BYTE), 
	"CHAT_ID" NUMBER(18,0), 
	"MESG_TEXT" VARCHAR2(4000 BYTE), 
	"MESG_TYPE" VARCHAR2(3 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"SERV_MESG_CODE" NUMBER(18,0), 
	"EROR_CODE" VARCHAR2(10 BYTE), 
	"EROR_MESG" VARCHAR2(100 BYTE), 
	"MESG_LENT" NUMBER(3,0), 
	"SEND_TYPE" VARCHAR2(3 BYTE), 
	"BULK_NUMB" NUMBER(18,0), 
	"PAGE_NUMB_DNRM" NUMBER(2,0), 
	"VIST_STAT" VARCHAR2(3 BYTE), 
	"VIST_DATE" DATE, 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."MESSAGE_BOX"."SEND_TYPE" IS 'تک به تک ارسال شده یا گروهی ارسال شده';
