--------------------------------------------------------
--  DDL for Table NEWS
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."NEWS" 
   (	"CODE" RAW(16), 
	"NEWS_NAME" VARCHAR2(100 BYTE), 
	"NEWS_DESC" VARCHAR2(500 BYTE), 
	"URL" VARCHAR2(500 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"SHOW_DATE" DATE, 
	"EXPR_DATE" DATE, 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."NEWS"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."NEWS"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."NEWS"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."NEWS"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."NEWS"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."NEWS"."DEL_DATE" IS 'تاریخ حذف';
