--------------------------------------------------------
--  Ref Constraints for Table PAYMENT_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."PAYMENT_TRANSACTION" ADD CONSTRAINT "FK_PTRN_PGAT" FOREIGN KEY ("PGAT_CODE")
	  REFERENCES "FCEO$KRNL"."PAYMENT_GATEWAY" ("CODE") ENABLE;
  ALTER TABLE "FCEO$KRNL"."PAYMENT_TRANSACTION" ADD CONSTRAINT "FK_PTRN_SYS" FOREIGN KEY ("SYS_CODE")
	  REFERENCES "FCEO$KRNL"."SYSTEM_APPLICATION" ("CODE") ENABLE;
