--------------------------------------------------------
--  Constraints for Table PAYMENT_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."PAYMENT_TRANSACTION" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."PAYMENT_TRANSACTION" ADD CONSTRAINT "PK_PTRN" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
