--------------------------------------------------------
--  DDL for Table PAYMENT_GATEWAY
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."PAYMENT_GATEWAY" 
   (	"HINF_CODE" RAW(16), 
	"CODE" RAW(16), 
	"PGAT_NAME" VARCHAR2(50 BYTE), 
	"PGAT_TYPE" VARCHAR2(3 BYTE), 
	"PSP_TYPE" VARCHAR2(3 BYTE), 
	"PGAT_DESC" VARCHAR2(100 BYTE), 
	"PGAT_DFLT" VARCHAR2(3 BYTE), 
	"PGAT_CNCT_TYPE" VARCHAR2(3 BYTE), 
	"IP_ADRS" VARCHAR2(15 BYTE), 
	"COMM_PORT" VARCHAR2(15 BYTE), 
	"PORT_NUMB" NUMBER, 
	"PRNT_SALE" VARCHAR2(250 BYTE), 
	"PRNT_CUST" VARCHAR2(250 BYTE), 
	"AUTO_COMM" VARCHAR2(3 BYTE), 
	"ACNT_TYPE" VARCHAR2(3 BYTE), 
	"BILL_FIND_TYPE" VARCHAR2(3 BYTE), 
	"BILL_NO" VARCHAR2(50 BYTE), 
	"TERM_NO" VARCHAR2(20 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_GATEWAY"."PGAT_TYPE" IS 'این گزینه برای مشخص کردن این هست که بگیم پوز هست یا درگاه پرداخت اینترنتی هست';
   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_GATEWAY"."PSP_TYPE" IS 'اینم مشخص میکنیم که چه شرکت PSP این خدمات رو به شما میده بابت این رکورد';
   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_GATEWAY"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_GATEWAY"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_GATEWAY"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_GATEWAY"."MDFY_DATE" IS 'تاریخ ویرایش';
