--------------------------------------------------------
--  DDL for Table PAYMENT_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."PAYMENT_TRANSACTION" 
   (	"PGAT_CODE" RAW(16), 
	"SYS_CODE" RAW(16), 
	"CODE" RAW(16), 
	"RQST_RQID" RAW(16), 
	"RQTP_CODE" VARCHAR2(3 BYTE), 
	"RWNO" NUMBER, 
	"TRAN_DATE" DATE, 
	"AMNT" NUMBER, 
	"PAY_STAT" VARCHAR2(3 BYTE), 
	"ISSU_DATE" DATE, 
	"RESP_CODE" VARCHAR2(3 BYTE), 
	"RESP_DESC" VARCHAR2(100 BYTE), 
	"TERM_NO" VARCHAR2(20 BYTE), 
	"TRAN_NO" VARCHAR2(20 BYTE), 
	"CARD_NO" VARCHAR2(16 BYTE), 
	"FLOW_NO" VARCHAR2(20 BYTE), 
	"REF_NO" VARCHAR2(20 BYTE), 
	"SERL_NO" VARCHAR2(20 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_TRANSACTION"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_TRANSACTION"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_TRANSACTION"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."PAYMENT_TRANSACTION"."MDFY_DATE" IS 'تاریخ ویرایش';
