--------------------------------------------------------
--  Constraints for Table PAYMENT_GATEWAY
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."PAYMENT_GATEWAY" MODIFY ("HINF_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."PAYMENT_GATEWAY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."PAYMENT_GATEWAY" ADD CONSTRAINT "PK_PGAT" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
