--------------------------------------------------------
--  DDL for Index PK_ASDM
--------------------------------------------------------

  CREATE UNIQUE INDEX "FCEO$KRNL"."PK_ASDM" ON "FCEO$KRNL"."APP_STATIC_DOMAIN" ("CODE", "VALU", "REGN_LANG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS" ;
