--------------------------------------------------------
--  DDL for Table PRIVILEGE
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."PRIVILEGE" 
   (	"BOXP_CODE" RAW(16), 
	"SYS_CODE" RAW(16), 
	"CODE" RAW(16), 
	"RWNO" NUMBER, 
	"PRVL_NAME" VARCHAR2(50 BYTE), 
	"PRVL_DESC" VARCHAR2(200 BYTE), 
	"STAT" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."PRIVILEGE"."BOXP_CODE" IS 'کد جعبه دسترسی';
   COMMENT ON COLUMN "FCEO$KRNL"."PRIVILEGE"."SYS_CODE" IS 'کد زیر سیستم';
   COMMENT ON COLUMN "FCEO$KRNL"."PRIVILEGE"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."PRIVILEGE"."RWNO" IS 'ردیف';
   COMMENT ON COLUMN "FCEO$KRNL"."PRIVILEGE"."PRVL_NAME" IS 'نام دسترسی';
   COMMENT ON COLUMN "FCEO$KRNL"."PRIVILEGE"."PRVL_DESC" IS 'توضیحات';
   COMMENT ON COLUMN "FCEO$KRNL"."PRIVILEGE"."STAT" IS 'وضعیت';
