--------------------------------------------------------
--  Constraints for Table ROLE_HISTORY
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."ROLE_HISTORY" MODIFY ("ROLE_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."ROLE_HISTORY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."ROLE_HISTORY" ADD CONSTRAINT "PK_ROLH" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
