--------------------------------------------------------
--  DDL for Table ROLE_PRIVILEGE_HISTORY
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."ROLE_PRIVILEGE_HISTORY" 
   (	"ROLP_CODE" RAW(16), 
	"CODE" RAW(16), 
	"CHNG_STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"CRET_HOST_BY" RAW(16)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE_HISTORY"."ROLP_CODE" IS 'کد نقش و دسترسی';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE_HISTORY"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE_HISTORY"."CHNG_STAT" IS 'وضعیت تغییر کرده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE_HISTORY"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE_HISTORY"."CRET_DATE" IS 'تاریخ ثبت';
