--------------------------------------------------------
--  Constraints for Table ROLE_SYSTEM_REPORT_HISTORY
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."ROLE_SYSTEM_REPORT_HISTORY" MODIFY ("RLSR_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."ROLE_SYSTEM_REPORT_HISTORY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."ROLE_SYSTEM_REPORT_HISTORY" ADD CONSTRAINT "PK_SRRH" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
