--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."ROLE" 
   (	"SYS_CODE" RAW(16), 
	"CODE" RAW(16), 
	"ROLE_NAME" VARCHAR2(50 BYTE), 
	"ROLE_DESC" VARCHAR2(200 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."SYS_CODE" IS 'کد زیر سیستم';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."ROLE_NAME" IS 'نام نقش';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."ROLE_DESC" IS 'توضیحات';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."STAT" IS 'وضعیت';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE"."DEL_DATE" IS 'تاریخ حذف';
