--------------------------------------------------------
--  DDL for Table ROLE_PRIVILEGE
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."ROLE_PRIVILEGE" 
   (	"ROLE_CODE" RAW(16), 
	"PRVL_CODE" RAW(16), 
	"CODE" RAW(16), 
	"STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."ROLE_CODE" IS 'کد نقش';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."PRVL_CODE" IS 'کد دسترسی';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."STAT" IS 'وضعیت';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_PRIVILEGE"."DEL_DATE" IS 'تاریخ حذف';
