--------------------------------------------------------
--  Constraints for Table ROLE_PRIVILEGE
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."ROLE_PRIVILEGE" MODIFY ("ROLE_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."ROLE_PRIVILEGE" MODIFY ("PRVL_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."ROLE_PRIVILEGE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."ROLE_PRIVILEGE" ADD CONSTRAINT "PK_ROLP" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
