--------------------------------------------------------
--  DDL for Table ROLE_SYSTEM_REPORT
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."ROLE_SYSTEM_REPORT" 
   (	"ROLE_CODE" RAW(16), 
	"SYSR_CODE" RAW(16), 
	"CODE" RAW(16), 
	"STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_SYSTEM_REPORT"."ROLE_CODE" IS 'کد نقش';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_SYSTEM_REPORT"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_SYSTEM_REPORT"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_SYSTEM_REPORT"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_SYSTEM_REPORT"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_SYSTEM_REPORT"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."ROLE_SYSTEM_REPORT"."DEL_DATE" IS 'تاریخ حذف';
