--------------------------------------------------------
--  Constraints for Table ROLE_PRIVILEGE_HISTORY
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."ROLE_PRIVILEGE_HISTORY" MODIFY ("ROLP_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."ROLE_PRIVILEGE_HISTORY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."ROLE_PRIVILEGE_HISTORY" ADD CONSTRAINT "PK_RLPH" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
