--------------------------------------------------------
--  DDL for Table SYSTEM_REPORT
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."SYSTEM_REPORT" 
   (	"SYSR_CODE" RAW(16), 
	"CODE" RAW(16), 
	"SYSR_NAME" VARCHAR2(100 BYTE), 
	"CMNT" VARCHAR2(250 BYTE), 
	"PATH_ADRS" VARCHAR2(500 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"RPRT_ENGN_TYPE" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_REPORT"."RPRT_ENGN_TYPE" IS 'Crystal Report Engine
Stimulsoft Report Engine';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_REPORT"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_REPORT"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_REPORT"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_REPORT"."MDFY_DATE" IS 'تاریخ ویرایش';
