--------------------------------------------------------
--  DDL for Table SYSTEM_APPLICATION
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."SYSTEM_APPLICATION" 
   (	"SYS_NAME" VARCHAR2(50 BYTE), 
	"SYS_DESC" VARCHAR2(200 BYTE), 
	"CODE" RAW(16), 
	"RWNO" NUMBER, 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_APPLICATION"."SYS_NAME" IS 'نام زیر سیستم';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_APPLICATION"."SYS_DESC" IS 'توضیحات';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_APPLICATION"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_APPLICATION"."RWNO" IS 'ردیف';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_APPLICATION"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_APPLICATION"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_APPLICATION"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_APPLICATION"."MDFY_DATE" IS 'تاریخ ویرایش';
