--------------------------------------------------------
--  Constraints for Table SYSTEM_AUDIT
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."SYSTEM_AUDIT" MODIFY ("USRA_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."SYSTEM_AUDIT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."SYSTEM_AUDIT" ADD CONSTRAINT "PK_SYSD" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
