--------------------------------------------------------
--  DDL for Table SYSTEM_AUDIT
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."SYSTEM_AUDIT" 
   (	"USRA_CODE" RAW(16), 
	"CODE" RAW(16), 
	"LOG_TYPE" VARCHAR2(3 BYTE), 
	"LOG_DESC" VARCHAR2(500 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_AUDIT"."USRA_CODE" IS 'کد کاربر';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_AUDIT"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_AUDIT"."LOG_TYPE" IS 'نوع لاگ';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_AUDIT"."LOG_DESC" IS 'توضیحات';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_AUDIT"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."SYSTEM_AUDIT"."CRET_DATE" IS 'تاریخ ثبت';
