REM INSERTING into FCEO$KRNL.SYSTEM_APPLICATION
SET DEFINE OFF;
Insert into FCEO$KRNL.SYSTEM_APPLICATION (SYS_NAME,SYS_DESC,CODE,RWNO,CRET_BY,CRET_DATE,MDFY_BY,MDFY_DATE) values ('KERNEL','هسته مرکزی و امنیتی سیستم','98B9B32A6FB246588F32DDFD4E17C527',1,null,null,null,null);
Insert into FCEO$KRNL.SYSTEM_APPLICATION (SYS_NAME,SYS_DESC,CODE,RWNO,CRET_BY,CRET_DATE,MDFY_BY,MDFY_DATE) values ('FCEO','نرم افزار سیستم جامع خدمات نظام مهندسی','8C2E4B401BF6486ABB905FFCFB2BCE67',2,null,null,null,null);
