--------------------------------------------------------
--  DDL for Table TABLE_ALIAS
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."TABLE_ALIAS" 
   (	"TABL_NAME" VARCHAR2(128 BYTE), 
	"TABL_DESC" VARCHAR2(500 BYTE), 
	"ALIS_NAME" VARCHAR2(4 BYTE), 
	"PROC_STAT" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;
