--------------------------------------------------------
--  Constraints for Table TEMPLATE_ITEM
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."TEMPLATE_ITEM" MODIFY ("TABL_NAME" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."TEMPLATE_ITEM" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."TEMPLATE_ITEM" ADD CONSTRAINT "PK_TMPI" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
