--------------------------------------------------------
--  DDL for Table TEMPLATE_ITEM
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."TEMPLATE_ITEM" 
   (	"TABL_NAME" VARCHAR2(128 BYTE), 
	"CODE" RAW(16), 
	"COLM_NAME" VARCHAR2(100 BYTE), 
	"PLAC_HLDR" VARCHAR2(100 BYTE), 
	"PLAC_DESC" VARCHAR2(100 BYTE), 
	"RECD_STAT" VARCHAR2(3 BYTE), 
	"COLM_VALU_TYPE" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."TEMPLATE_ITEM"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."TEMPLATE_ITEM"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."TEMPLATE_ITEM"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."TEMPLATE_ITEM"."MDFY_DATE" IS 'تاریخ ویرایش';
