--------------------------------------------------------
--  Ref Constraints for Table USER_APPLICATION_INSTANCE
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE" ADD CONSTRAINT "FK_UAIN1_USRA" FOREIGN KEY ("USRA_CODE")
	  REFERENCES "FCEO$KRNL"."USER_APPLICATION" ("CODE") ENABLE;
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE" ADD CONSTRAINT "FK_UAIN2_USRA" FOREIGN KEY ("UINS_CODE")
	  REFERENCES "FCEO$KRNL"."USER_APPLICATION" ("CODE") ENABLE;
