--------------------------------------------------------
--  DDL for Table USER_APPLICATION_ROLE_HISTORY
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."USER_APPLICATION_ROLE_HISTORY" 
   (	"UARL_CODE" RAW(16), 
	"CODE" RAW(16), 
	"CHNG_STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"CRET_HOST_BY" RAW(16)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_ROLE_HISTORY"."UARL_CODE" IS 'کد کاربر و نقش';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_ROLE_HISTORY"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_ROLE_HISTORY"."CHNG_STAT" IS 'وضعیت تغییر';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_ROLE_HISTORY"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_ROLE_HISTORY"."CRET_DATE" IS 'تاریخ ثبت';
