--------------------------------------------------------
--  DDL for Table USER_APPLICATION_PAYMENT_GATEWAY
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY" 
   (	"USRA_CODE" RAW(16), 
	"PGAT_CODE" RAW(16), 
	"CODE" RAW(16), 
	"STAT" VARCHAR2(3 BYTE), 
	"BILL_NO" VARCHAR2(50 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY"."MDFY_DATE" IS 'تاریخ ویرایش';
