--------------------------------------------------------
--  Ref Constraints for Table USER_REFRESH_TOKEN
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_REFRESH_TOKEN" ADD CONSTRAINT "FK_URTK_USON" FOREIGN KEY ("USON_CODE")
	  REFERENCES "FCEO$KRNL"."USER_HOST_SESSION" ("CODE") ENABLE;
  ALTER TABLE "FCEO$KRNL"."USER_REFRESH_TOKEN" ADD CONSTRAINT "FK_RURT_URTK" FOREIGN KEY ("RPLC_BY_TOKN_CODE")
	  REFERENCES "FCEO$KRNL"."USER_REFRESH_TOKEN" ("CODE") ENABLE;
  ALTER TABLE "FCEO$KRNL"."USER_REFRESH_TOKEN" ADD CONSTRAINT "FK_URTK_USRA" FOREIGN KEY ("USRA_CODE")
	  REFERENCES "FCEO$KRNL"."USER_APPLICATION" ("CODE") ENABLE;
