--------------------------------------------------------
--  DDL for Table USER_APPLICATION_INSTANCE
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE" 
   (	"USRA_CODE" RAW(16), 
	"UINS_CODE" RAW(16), 
	"CODE" RAW(16), 
	"STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."USRA_CODE" IS 'کد کاربر مبدا';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."UINS_CODE" IS 'کد کاربر نمونه مقصد';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."STAT" IS 'وضعیت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION_INSTANCE"."DEL_DATE" IS 'تاریخ حذف';
