--------------------------------------------------------
--  Constraints for Table USER_HOST_SESSION
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_HOST_SESSION" MODIFY ("HINF_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_HOST_SESSION" MODIFY ("USRA_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_HOST_SESSION" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_HOST_SESSION" ADD CONSTRAINT "PK_USON" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
