--------------------------------------------------------
--  Ref Constraints for Table USER_APPLICATION_PRIVILEGE
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_PRIVILEGE" ADD CONSTRAINT "FK_UAPR_PRVL" FOREIGN KEY ("PRVL_CODE")
	  REFERENCES "FCEO$KRNL"."PRIVILEGE" ("CODE") ENABLE;
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_PRIVILEGE" ADD CONSTRAINT "FK_UAPR_USRA" FOREIGN KEY ("USRA_CODE")
	  REFERENCES "FCEO$KRNL"."USER_APPLICATION" ("CODE") ENABLE;
