--------------------------------------------------------
--  DDL for Table USER_HOST_SESSION
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."USER_HOST_SESSION" 
   (	"HINF_CODE" RAW(16), 
	"USRA_CODE" RAW(16), 
	"CODE" RAW(16), 
	"APP_SNID" VARCHAR2(100 BYTE), 
	"LOG_IN_DATE" DATE, 
	"LOG_OUT_DATE" DATE, 
	"LOG_SEEN_DATE" DATE, 
	"ACTV_STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."HINF_CODE" IS 'کد دستگاه متصل';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."USRA_CODE" IS 'کد کاربر';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."APP_SNID" IS 'شماره سشن نرم افزار';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."LOG_IN_DATE" IS 'تاریخ ورود';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."LOG_OUT_DATE" IS 'تاریخ خروج';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."LOG_SEEN_DATE" IS 'تاریخ آخرین رویکرد';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."ACTV_STAT" IS 'وضعیت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_HOST_SESSION"."MDFY_DATE" IS 'تاریخ ویرایش';
