--------------------------------------------------------
--  DDL for Table USER_NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."USER_NOTIFICATION" 
   (	"NEWS_CODE" RAW(16), 
	"USRA_CODE" RAW(16), 
	"CODE" RAW(16), 
	"NOTF_DESC" VARCHAR2(500 BYTE), 
	"NOFT_NAME" VARCHAR2(100 BYTE), 
	"READ_STAT" VARCHAR2(3 BYTE), 
	"PIN_STAT" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;
