--------------------------------------------------------
--  Ref Constraints for Table USER_APPLICATION_PAYMENT_GATEWAY
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY" ADD CONSTRAINT "FK_UAPG_PGAT" FOREIGN KEY ("PGAT_CODE")
	  REFERENCES "FCEO$KRNL"."PAYMENT_GATEWAY" ("CODE") ENABLE;
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY" ADD CONSTRAINT "FK_UAPG_USRA" FOREIGN KEY ("USRA_CODE")
	  REFERENCES "FCEO$KRNL"."USER_APPLICATION" ("CODE") ENABLE;
