--------------------------------------------------------
--  Constraints for Table USER_APPLICATION_INSTANCE_HISTORY
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE_HISTORY" MODIFY ("UAIN_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE_HISTORY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE_HISTORY" ADD CONSTRAINT "PK_UAIH" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
