--------------------------------------------------------
--  Constraints for Table USER_IMAGE
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_IMAGE" MODIFY ("USRA_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_IMAGE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_IMAGE" ADD CONSTRAINT "PK_UIMG" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
