--------------------------------------------------------
--  Constraints for Table USER_REFRESH_TOKEN
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_REFRESH_TOKEN" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_REFRESH_TOKEN" MODIFY ("USRA_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_REFRESH_TOKEN" MODIFY ("USON_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_REFRESH_TOKEN" MODIFY ("RPLC_BY_TOKN_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_REFRESH_TOKEN" ADD CONSTRAINT "PK_URTK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
