--------------------------------------------------------
--  Constraints for Table USER_APPLICATION_PAYMENT_GATEWAY
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY" MODIFY ("USRA_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY" MODIFY ("PGAT_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_PAYMENT_GATEWAY" ADD PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
