--------------------------------------------------------
--  Constraints for Table USER_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_NOTIFICATION" MODIFY ("NEWS_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_NOTIFICATION" MODIFY ("USRA_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_NOTIFICATION" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_NOTIFICATION" ADD CONSTRAINT "PK_UNOT" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
