--------------------------------------------------------
--  Constraints for Table USER_APPLICATION_ROLE_HISTORY
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_ROLE_HISTORY" MODIFY ("UARL_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_ROLE_HISTORY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_ROLE_HISTORY" ADD CONSTRAINT "PK_UARH" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
