--------------------------------------------------------
--  DDL for Table USER_REFRESH_TOKEN
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."USER_REFRESH_TOKEN" 
   (	"CODE" RAW(16), 
	"USRA_CODE" RAW(16), 
	"USON_CODE" RAW(16), 
	"TOKN_HASH" VARCHAR2(500 BYTE), 
	"TOKN_FMLY_CODE" RAW(16), 
	"ISSU_DATE" DATE, 
	"EXPR_DATE" DATE, 
	"REVK_DATE" DATE, 
	"REVK_RESN_TYPE" VARCHAR2(3 BYTE), 
	"REVK_RESN_DESC" VARCHAR2(500 BYTE), 
	"RPLC_BY_TOKN_CODE" RAW(16), 
	"ACTV_STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."USRA_CODE" IS 'کد کاربر';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."USON_CODE" IS 'کد سشن دستگاه';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."TOKN_HASH" IS 'توکن هش شده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."TOKN_FMLY_CODE" IS 'توکن پرنت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."ISSU_DATE" IS 'تاریخ صدور';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."EXPR_DATE" IS 'تاریخ انقضا';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."REVK_DATE" IS 'تاریخ رد کردن';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."REVK_RESN_TYPE" IS 'نوع دلیل رد کردن توکن';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."REVK_RESN_DESC" IS 'توضیحات دلیل رد کردن توکن';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."RPLC_BY_TOKN_CODE" IS 'کد توکن های جایگزین';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."ACTV_STAT" IS 'وضعیت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_REFRESH_TOKEN"."MDFY_DATE" IS 'تاریخ ویرایش';
