--------------------------------------------------------
--  DDL for Table USER_IMAGE
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."USER_IMAGE" 
   (	"USRA_CODE" RAW(16), 
	"CODE" RAW(16), 
	"RWNO" NUMBER, 
	"IMAG" CLOB, 
	"IMAG_TYPE" VARCHAR2(3 BYTE), 
	"IMAG_DESC" VARCHAR2(100 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"CRET_BY" VARCHAR2(30 BYTE), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 BYTE), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 BYTE), 
	"DEL_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY 
 LOB ("IMAG") STORE AS SECUREFILE (
  TABLESPACE "FCEO_KRNL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."USRA_CODE" IS 'کد کاربر';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."RWNO" IS 'ردیف';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."IMAG" IS 'عکس';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."IMAG_TYPE" IS 'نوع عکس';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."IMAG_DESC" IS 'توضیحات';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."STAT" IS 'وضعیت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_IMAGE"."DEL_DATE" IS 'تاریخ حذف';
