--------------------------------------------------------
--  DDL for Table USER_APPLICATION
--------------------------------------------------------

  CREATE TABLE "FCEO$KRNL"."USER_APPLICATION" 
   (	"CODE" RAW(16), 
	"USER_APP_NAME" VARCHAR2(30 CHAR), 
	"USER_APP_DESC" VARCHAR2(100 CHAR), 
	"PASS_WORD" RAW(256), 
	"SALT_KEY" RAW(32), 
	"PIN_CODE" RAW(256), 
	"SMS_CODE" VARCHAR2(6 CHAR), 
	"QR_LINK_DEV_CODE" VARCHAR2(100 CHAR), 
	"STIC_2FA_CODE" RAW(256), 
	"DYNC_2FA_CODE" VARCHAR2(100 CHAR), 
	"TOTP_SCRT_KEY" VARCHAR2(64 CHAR), 
	"TOTP_STAT" VARCHAR2(3 CHAR), 
	"LAST_USE_TIME" TIMESTAMP (0), 
	"LAST_TOTP_STEP" NUMBER, 
	"FRST_LOGN_STAT" VARCHAR2(3 CHAR), 
	"MUST_CHNG_PASS" VARCHAR2(3 CHAR), 
	"LAST_UPDT_PASS" DATE, 
	"STAT" VARCHAR2(3 CHAR), 
	"CMNT" VARCHAR2(200 CHAR), 
	"PHON_NUMB" VARCHAR2(15 CHAR), 
	"REGN_LANG" VARCHAR2(3 CHAR), 
	"EMAL_ADRS" VARCHAR2(254 CHAR), 
	"EMAL_VERF_STAT" VARCHAR2(3 CHAR), 
	"FALD_LGIN_CONT" NUMBER(5,0), 
	"LOCK_END_TIME" TIMESTAMP (0), 
	"CRET_BY" VARCHAR2(30 CHAR), 
	"CRET_DATE" DATE, 
	"MDFY_BY" VARCHAR2(30 CHAR), 
	"MDFY_DATE" DATE, 
	"DEL_BY" VARCHAR2(30 CHAR), 
	"DEL_DATE" DATE, 
	"VIEW_PAGE_SIZE" NUMBER(3,0), 
	"USRA_CODE" RAW(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCEO_KRNL_TS"   NO INMEMORY ;

   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."CODE" IS 'کد یکتا';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."USER_APP_NAME" IS 'نام کاربری';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."USER_APP_DESC" IS 'عنوان کاربری سیستم';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."PASS_WORD" IS 'رمز عبور';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."SALT_KEY" IS 'کلید هش کردن اطلاعات رمز عبور';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."PIN_CODE" IS 'رمز چهار و شش رقمی پین کد';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."SMS_CODE" IS 'رمز یکبار مصرف پیامکی';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."QR_LINK_DEV_CODE" IS 'لینک بارکد برقراری اتصال با کاربر';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."STIC_2FA_CODE" IS 'کد دو مرحله ای ثابت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."DYNC_2FA_CODE" IS 'کد دو مرحله ای داینامیک';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."TOTP_SCRT_KEY" IS 'رمز کلید دو مرحله ای';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."TOTP_STAT" IS 'فعال بودن گزینه کد دو مرحله ای';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."LAST_USE_TIME" IS 'آخرین تایم دیدن کد دو مرحله ای';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."LAST_TOTP_STEP" IS 'آخرین مرحله استفاده از کد دو مرحله ای';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."FRST_LOGN_STAT" IS 'وضعیت اولین لاگین';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."MUST_CHNG_PASS" IS 'ایا نیاز به تغییر رمز به صورت اجباری وجود دارد؟';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."LAST_UPDT_PASS" IS 'آخرین زمان بروزرسانی کد های امنیتی';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."STAT" IS 'وضعیت کاربر';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."CMNT" IS 'توضیحات';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."PHON_NUMB" IS 'شماره موبایل';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."REGN_LANG" IS 'زبان';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."EMAL_ADRS" IS 'آدرس ایمیل';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."EMAL_VERF_STAT" IS 'وضعیت تاییدیه ایمیل';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."FALD_LGIN_CONT" IS 'تعداد دفعات اشتباه در ورود';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."LOCK_END_TIME" IS 'مدت زمان قفل بودن کاربر';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."CRET_BY" IS 'کاربر ثبت کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."CRET_DATE" IS 'تاریخ ثبت';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."MDFY_BY" IS 'کاربر ویرایش کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."MDFY_DATE" IS 'تاریخ ویرایش';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."DEL_BY" IS 'کاربر حذف کننده';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."DEL_DATE" IS 'تاریخ حذف';
   COMMENT ON COLUMN "FCEO$KRNL"."USER_APPLICATION"."VIEW_PAGE_SIZE" IS 'اندازه تعداد رکورد برگشتی در هر صفحه';
