--------------------------------------------------------
--  Constraints for Table USER_APPLICATION_INSTANCE
--------------------------------------------------------

  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE" MODIFY ("USRA_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE" MODIFY ("UINS_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FCEO$KRNL"."USER_APPLICATION_INSTANCE" ADD CONSTRAINT "PK_UAIN" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "FCEO_KRNL_TS"  ENABLE;
